kernel:
  image: darwinkit/kernel:4.19.34
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - darwinkit/init:v0.7
  - darwinkit/runc:v0.7
  - darwinkit/containerd:v0.7
  - darwinkit/ca-certificates:v0.7
  - hyperledgerlabs/darwinkit-java:latest
onboot:
  - name: sysctl
    image: darwinkit/sysctl:v0.7
  - name: dhcpcd
    image: darwinkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: darwinkit/metadata:v0.7
services:
  - name: rngd
    image: darwinkit/rngd:v0.7
